### ISSUE TITLE
Create the Startup Profiles Page using Material UI Cards

### ISSUE THREAD

**Issue by julianjear** [XRoads/Site#11]
- 3 cards per row unless device size is smaller

Each card will have the following:
- Logo (if no logo, default picture)
- Name of startup
- Description (if too big to fit, make it scrollable)
- number of open roles 
- Posted date (the date the profile was created, not the date the startup was established) I am not sure if there is currently a timestamp of when the profile was created. If it is not there, please create it.

**Comment by julianjear** [comment]
Sample UI image:
![StartupProfilesPage](https://user-images.githubusercontent.com/31468425/65379920-08a8dc00-dc96-11e9-967a-108ce02f335d.jpeg)

**Comment by Mahfouzer** [comment]
there's no endpoint with the name 'startup' in it 
can you please specify which one to pull data from?
